# Generated by Django 4.2.5 on 2023-12-20 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='video',
        ),
    ]
