# Generated by Django 4.2.5 on 2024-01-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_encoding_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='encoding',
            name='changed_frame_after_encoding',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
