# Generated by Django 4.2.5 on 2024-01-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_encoding_changed_frame_after_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encoding',
            name='encoded_file',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
