# Generated by Django 4.2.5 on 2024-01-16 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_encoding_encoded_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decoding',
            old_name='file',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='encoding',
            old_name='file',
            new_name='video',
        ),
    ]
