# Generated by Django 4.2.5 on 2024-01-16 04:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_file_decoding_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encoding',
            name='changed_frame_after_encoding',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), size=8), size=8),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='encoded_file',
            field=models.FileField(null=True, upload_to='encoded/'),
        ),
    ]
