# Generated by Django 4.2.5 on 2024-01-18 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_file_decoding_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decoding',
            name='frame_number',
        ),
        migrations.RemoveField(
            model_name='encoding',
            name='changed_frame_after_encoding',
        ),
        migrations.AddField(
            model_name='encoding',
            name='encoded_file_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='decoding',
            name='video',
            field=models.FileField(null=True, upload_to='decoded/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MP4', 'AVI'])], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='encoded_file',
            field=models.FileField(null=True, upload_to='encoded/'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MP4', 'AVI'])], verbose_name=''),
        ),
    ]
