# Generated by Django 4.2.5 on 2024-01-20 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_decoding_frame_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encoding',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['AVI'])], verbose_name=''),
        ),
    ]
