# Generated by Django 4.2.5 on 2024-01-22 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_encoding_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoding',
            name='secret_key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='decoding',
            name='video',
            field=models.FileField(null=True, upload_to='decoded/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['AVI'])], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='encoded_file_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='secret_key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
