# Generated by Django 4.2.5 on 2024-01-17 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_encoding_changed_frame_after_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encoding',
            name='changed_frame_after_encoding',
        ),
        migrations.AlterField(
            model_name='decoding',
            name='video',
            field=models.FileField(null=True, upload_to='decoded/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MP4'])], verbose_name=''),
        ),
    ]
