# Generated by Django 4.2.5 on 2024-01-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_encoding_changed_frame_after_encoding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encoding',
            name='encoded_file_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
