# Generated by Django 4.2.5 on 2024-01-18 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_encoding_encoded_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decoding',
            name='frame_number',
        ),
        migrations.AlterField(
            model_name='decoding',
            name='video',
            field=models.FileField(null=True, upload_to='decoded/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MP4', 'AVI'])], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MP4', 'AVI'])], verbose_name=''),
        ),
    ]
