# Generated by Django 4.2.5 on 2024-01-22 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageSteg', '0002_alter_imageencoding_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageencoding',
            name='user',
        ),
    ]
